services:
  - type: web
    name: auth-app-premium
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: "bin/rails db:prepare && bin/rails server"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: auth-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false

databases:
  - name: auth-db
    plan: free
